# Generated by Django 5.2.7 on 2025-10-13 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('CL', 'CLASSIC'), ('HL', 'HONEY'), ('GR', 'GINGER'), ('SL', 'SPECIAL'), ('KW', 'KASHMIRI'), ('KT', 'KIWI'), ('LT', 'LEMON')], default='CL', max_length=2)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
